### ISSUE TITLE
Material para utilização da lib

### ISSUE THREAD

**Issue by Marcelo-Kyan** [marcydoty/Recursos-NFE-em-Python#13]
Oi Marcilene,
Você teria algum material exemplificando o uso dessa lib?
Estou tentando mas está difícil.

**Comment by marcydoty** [comment]
Oi Marcelo, estou fazendo um lançamento de projeto hoje, infelizmente não
pude responder, mas assim que possível lhe respondo direito, blz?
Manual, eu não tenho, vou ter que montar um exemplo pra vc. Assim que
possível farei isso. Hoje no meu trabalho estou tendo muitas solicitações por
causa do lançamento de um projeto, por isso estou meio sem tempo.
Assim que possível lhe respondo.

Abraços,

**Comment by Marcelo-Kyan** [comment]
Valeu, eu aguardo

**Comment by Marcelo-Kyan** [comment]
E aí Marcilene, sobrou algum tempinho?
Desculpe estar te enchendo, mas estou realmente bem interessado em colocar pra funcionar.
Desde já muito obrigado

**Comment by Marcelo-Kyan** [comment]
Marcilene, alguma novidade?

**Comment by Marcelo-Kyan** [comment]
Oi Marcilene,
Sobrou um tempinho para tentar resolver meu problema?

**Comment by marcydoty** [comment]
Oi Marcelo, desculpe a demora, realmente estou com muito serviço aqui. Fiz um pequeno exemplo só pra vc ir adiantando.

```python
from nfe.nf_e import *        
n = nf_e()
xml = "string do xml da nfe"
conteudo_certificado = "string do conteúdo do certificado"
chave = "string chave do certificado
versao = "2.0"
ambiente = "2" #homologacao ou producao nesse caso homologacao
estado = "MG"

n.processar_nfe(xml,
		conteudo_certificado,
		chave,
		versao, 
		ambiente,
		estado)

```

**Comment by Marcelo-Kyan** [comment]
Oi Marcilene,
Acho que tem alguma coisa errada.
Veja o erro que dá:
Traceback (most recent call last):
  File "./processar_nfe1.py", line 25, in <module>
    resp = i.processar_nfe(xml,cert,key,versao,ambiente,estado,contingencia)
  File "/usr/lib/python2.7/site-packages/python_nfe-3.8-py2.7.egg/nfe/nf_e.py", line 109, in processar_nfe
    for processo in p.processar_notas([n]):
  File "/usr/lib/python2.7/site-packages/python_nfe-3.8-py2.7.egg/nfe/pysped/nfe/processador_nfe.py", line 886, in processar_notas
    proc_envio, novos_arquivos = self.enviar_lote(lista_nfes=lista_nfes)
  File "/usr/lib/python2.7/site-packages/python_nfe-3.8-py2.7.egg/nfe/pysped/nfe/processador_nfe.py", line 247, in enviar_lote
    self.certificado.assina_xmlnfe(nfe)
  File "/usr/lib/python2.7/site-packages/python_nfe-3.8-py2.7.egg/nfe/pysped/xml_sped/certificado.py", line 165, in assina_xmlnfe
    xml = self.assina_xml(doc.xml)
  File "/usr/lib/python2.7/site-packages/python_nfe-3.8-py2.7.egg/nfe/pysped/xml_sped/certificado.py", line 237, in assina_xml
    self._inicia_funcoes_externas()
  File "/usr/lib/python2.7/site-packages/python_nfe-3.8-py2.7.egg/nfe/pysped/xml_sped/certificado.py", line 147, in _inicia_funcoes_externas
    xmlsec.cryptoAppInit(None)
AttributeError: 'module' object has no attribute 'cryptoAppInit'

**Comment by Marcelo-Kyan** [comment]
Oi Marcilene,
Só pra te informar, conseguí solucionar o problema anterior, era conflito de libs.
Agora estou tentando enviar a tad <dhSaiEnt> em branco, pois não quero preencher a data de saida da nota.

**Comment by Marcelo-Kyan** [comment]
tag dhSaiEnt em branco.

**Comment by marcydoty** [comment]
Oi Marcelo, tenta colocar só a data de saída  com a data atual e a hora com  "00:00:00 ", pois é um campo obrigatório para alguns estados.

Abraços
