### ISSUE TITLE
Erro ao utilizar um certificado novo

### ISSUE THREAD

**Issue by Marcelo-Kyan** [marcydoty/Recursos-NFE-em-Python#24]
Bom dia Marcilene,
 
Recebí um certificado (arquivo .pfx) fde um cliente e quando tento utilizá-lo me retorna o seguinte erro.
 
Traceback (most recent call last):
  File "./extrair_a1.py", line 17, in <module>
    certificado = instancia.extrair_certificado_a1(file(arquivo, 'rb').read(),senha)
  File "/usr/lib/python2.7/site-packages/nfe/nf_e.py", line 30, in extrair_certificado_a1
    conteudo_pkcs12 = crypto.load_pkcs12(arquivo, senha)
  File "/usr/lib/python2.7/site-packages/OpenSSL/crypto.py", line 2225, in load_pkcs12
    _raise_current_error()
  File "/usr/lib/python2.7/site-packages/OpenSSL/_util.py", line 22, in exception_from_error_queue
    raise exceptionType(errors)
OpenSSL.crypto.Error: [('PKCS12 routines', 'PKCS12_parse', 'mac verify failure')]
 
 Você sabe o que pode estar errado?
 
Obrigado

**Comment by Marcelo-Kyan** [comment]
Oi Marcilene, esquece a questão anterior.
Eu estava utilizando uma senha errada para o certificado.
